Let's try this once more. Poolchems, activate!
HippieStationArchive/HippieStation13-1 pull request #2918
Opened 2016-09-17 19:31 UTC by Kokojos

This PR has been accepted before but needed better code, link to prior PR here : 
https://github.com/HippieStationCode/HippieStation13/pull/2711

Also fixes a minor visual bug in the display of the pool controller.

With this you can melt objects in the pool!
Make getting cryo!
Turn everyone in the pool black with spraytan!
And much more!

2016-09-17 19:49 UTC, McBawbaggings commented
Can I turn people black with spray with this?

2016-09-17 19:50 UTC, McBawbaggings commented
WELL FUCK I DIDN'T READ THE DESCRIPTION
+1

2016-09-17 19:52 UTC, McBawbaggings commented
Holy fuck you're working off of your master JFC

2016-09-17 19:54 UTC, Kokojos commented
Yeah I merged this into my master because I had so many trouble with the map earlier din't want to take any chances. Il redownload when this passes anyway.

2016-09-17 23:09 UTC, ArcLumin commented
+0.1 finally gonna put randomizer toxin in it

2016-09-18 20:40 UTC, Carbonhell commented on code/game/machinery/poolcontroller.dm
> +			if(src.beaker)
src.

2016-09-18 20:40 UTC, Carbonhell commented on code/game/machinery/poolcontroller.dm
> +				src.beaker =  W
src.

2016-09-18 20:41 UTC, Carbonhell commented on code/game/machinery/poolcontroller.dm
> +				user << "<span class='notice'>This machine only accepts full beakers of one reagent.</span>"
full LARGE beakers*

2016-09-18 20:43 UTC, Carbonhell requested changes

2016-09-19 04:57 UTC, Kokojos commented on code/game/machinery/poolcontroller.dm
> +				src.beaker =  W
fixed

2016-09-19 04:57 UTC, Kokojos commented on code/game/machinery/poolcontroller.dm
> +			if(src.beaker)
fixed

2016-09-19 04:57 UTC, Kokojos commented on code/game/machinery/poolcontroller.dm
> +				user << "<span class='notice'>This machine only accepts full beakers of one reagent.</span>"
fixed

2016-09-19 15:55 UTC, doobiedoo23 commented
i think i +1/3ed the old one let's do it

2016-09-19 18:31 UTC, Carbonhell approved these changes

2016-09-19 18:34 UTC, merged