VAPE NATION take 2
HippieStationArchive/HippieStation13-1 pull request #2937
Opened 2016-09-25 20:17 UTC by tortellinitony

https://github.com/tgstation/tgstation/pull/20629

Adds vape and a gnarly shirt to show off that it's just vape bro!

2016-09-25 20:36 UTC, dreamcrab commented
does it blow smoke clouds that people cant see through

2016-09-25 20:37 UTC, tortellinitony commented
if emagged it makes big smoke clouds of whatever chemical you have

2016-09-25 21:00 UTC, Nebyab commented
Isn't this an in-progress pr? 

I have mild concerns about porting it, if that is the case.

Otherwise, sure why not.

2016-09-25 21:29 UTC, tortellinitony commented
TG merged it and it works as far as I can tell, but whatever you think.

2016-09-25 22:57 UTC, doobiedoo23 commented
>he didn't name his branch vapestation

+1

2016-09-26 07:07 UTC, banthebantz commented
YES

2016-09-26 19:10 UTC, McBawbaggings commented
GIVE US ANOTHER ONE
GIVE US ANOTHER ONE
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
+1 even tho it's pretty degenerate ;^)

2016-09-26 19:16 UTC, Cuboos commented
Darn hippies stealing my PR.

2016-09-26 19:38 UTC, McBawbaggings commented on code/game/objects/items/weapons/cigs_lighters.dm
> +				user << "<span class='notice'>You add the contents of [O] to the [src]</span>"
Add a . to the end.

2016-09-26 19:38 UTC, McBawbaggings commented on code/game/objects/items/weapons/cigs_lighters.dm
> +			user << "<span class='notice'>You open the cap on the [src]</span>"
Add a . to the end.

2016-09-26 19:39 UTC, McBawbaggings commented on code/game/objects/items/weapons/cigs_lighters.dm
> +			user << "<span class='notice'>You close the cap on the [src]</span>"
Add a . to the end.

2016-09-26 19:39 UTC, McBawbaggings commented on code/game/objects/items/weapons/cigs_lighters.dm
> +				user << "<span class='notice'>You increase the voltage in the [src]</span>"
Add a . to the end.

2016-09-26 19:39 UTC, McBawbaggings commented on code/game/objects/items/weapons/cigs_lighters.dm
> +				user << "<span class='notice'>You decrease the voltage in the [src]</span>"
Add a . to the end.

2016-09-26 19:39 UTC, McBawbaggings commented on code/game/objects/items/weapons/cigs_lighters.dm
> +			user << "<span class='warning'>You maximize the voltage in the [src]</span>"
Add a ! to the end.

2016-09-26 19:39 UTC, McBawbaggings commented on code/game/objects/items/weapons/cigs_lighters.dm
> +			user << "<span class='notice'>You start puffing on that dank vape</span>"
Add a . to the end.

2016-09-26 19:40 UTC, McBawbaggings commented on code/modules/clothing/suits/miscellaneous.dm
> +	name = "Vape Naysh shirt"
Aren't names meant not to start with capitals?

2016-09-26 19:40 UTC, McBawbaggings commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A cheap white T-shirt with a big tacky \"VN\" on the front, Why would you wear this unironicly?"
Unironically.

2016-09-26 19:41 UTC, McBawbaggings commented on code/game/objects/items/weapons/cigs_lighters.dm
> +		user << "<span class='notice'>You need to open the cap to do that</span>"
Add a . to the end.

2016-09-26 19:42 UTC, McBawbaggings commented on code/game/objects/items/weapons/cigs_lighters.dm
> +		user << "<span class='notice'>you empty [src] of all reagents.</span>"
Capital letter required.

2016-09-26 19:42 UTC, ghost requested changes
Fix up the text please.

2016-09-26 19:43 UTC, McBawbaggings commented
Hold on that +1 for me until you fix up the flavor text please.

2016-09-26 19:49 UTC, ArcLumin commented
@Cuboos You know it lad.

2016-09-26 21:06 UTC, tortellinitony commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A cheap white T-shirt with a big tacky \"VN\" on the front, Why would you wear this unironicly?"
How culd they murge such a atrosity

2016-09-26 23:06 UTC, tortellinitony commented
Fixed the grammar

2016-09-27 07:42 UTC, SplergeBucket commented
hel yeha

2016-09-28 20:38 UTC, tortellinitony commented
By the way, you can vape donuts...

2016-09-28 20:41 UTC, FuryMcFlurry commented
not a bug to me

2016-09-29 16:30 UTC, Pyko1 commented
fix the missing dot that mcbaws wanted to be fixed and then it should be ready to be merged.

2016-09-29 19:10 UTC, tortellinitony commented
the punctuation should be all fixed now

2016-09-29 19:14 UTC, Pyko1 commented
seems fine, merging.

2016-09-29 19:14 UTC, merged

2016-09-29 19:14 UTC, banthebantz commented
yes boys

2016-10-02 12:03 UTC, optimumtact commented
it's tg not TG