Makes it a bit easier to get tech shells.
HippieStationArchive/HippieStation13-1 pull request #3082
Opened 2016-12-07 15:01 UTC by GuyonBroadway

Tech shells are fun but rarely useful, or used. This won't do much for regular R&D but it will make it so anyone doing Drive-by R&D will be able to get tech-shells and make fun shit like meteor shot and dragons-breath rounds.

Also the pulse slug shell still needs ultra high power microlasers so it's not like we're going to see people running around with ghetto deathsquad shotguns within 30 seconds of roundstart. 

And none of that stuff is anywhere NEAR as good as shotgun darts which are buildable in the autolathe WITHOUT any tech from R&D.

2016-12-07 15:04 UTC, McBawbaggings commented
Nah, mining has gotten some serious buffs. Science doesn't need to be stronger.

2016-12-07 15:06 UTC, GuyonBroadway commented
It's hardly making science stronger, all it takes is a few parts from robotics to get these shells and as it stands they are nowhere near as good as easier to get stuff. It's a buff for ghetto R&D at best, or for situations where miners are unlikey to deliver and science is unlikely to get done, such as rev or gang rounds. 

Plus, when do you EVER see meteor shot?

2016-12-07 19:39 UTC, ArcLumin commented
I use meteor shot. It's amazingly good.

But yeah, I agree, tech shells need to be easier to get, but forget doing it THAT way. Rather, make them able to be tablecrafted

2016-12-07 19:42 UTC, banthebantz commented
Make them maint loot or something.

2016-12-14 10:09 UTC, Pyko1 commented
Maintloot tablecraft shit for techshells would be awesome.

2016-12-24 08:47 UTC, ArcLumin commented
Code's good.

2016-12-24 16:04 UTC, SplergeBucket commented
Turn combat and materials to 3 and I'm good wit it.

2016-12-29 16:54 UTC, JohnGinnane requested changes

2016-12-29 16:54 UTC, JohnGinnane commented
Need head input or I'll close

2016-12-29 16:56 UTC, McBawbaggings commented
As said, I'm very apprehensive to give science buffs considering the amount of mining buffs there have been.

2016-12-29 16:56 UTC, GuyonBroadway commented on html/changelogs/GuyonBroadway - Easier Techshells.yml
> +author: N3X15
Whoops, im away from master pc till tomorrow, I'll fix it then.

2016-12-29 16:57 UTC, JohnGinnane commented
What can be done to fix that?

2016-12-29 17:02 UTC, GuyonBroadway commented
My argument is that science could easily get tech shells as part of normal r&d anyway AND the components needed to make some of the more powerful tech shells are gated behind materials anyway. This is just so some pluck cargo tech can pop in, do some quick drive by by r&d, grab a few tech shells and go do whatever.

2016-12-30 17:51 UTC, GuyonBroadway commented
Ok changelog fixed all good and propah.

2016-12-30 19:08 UTC, Swagile commented
Im gunna give my GM + 1 on this considering its not really that much of a puff as only cargo really uses shotguns, and good luck plucking their combat shotguns out of their cold dying hands.

2017-01-02 04:10 UTC, SpankMasterson commented
I'm willing to give it a try +1

2017-01-03 23:36 UTC, JohnGinnane approved these changes

2017-01-03 23:36 UTC, JohnGinnane commented
This is ready, just need head input

2017-01-06 08:04 UTC, Swagile commented
we have 3/6 votes on this since 1 headmin voted and 1 GM voted

2017-01-07 01:29 UTC, JohnGinnane commented
Heads have approved, merging

2017-01-07 01:29 UTC, merged