More Explosion logging
HippieStationArchive/HippieStation13-1 pull request #3186
Opened 2016-12-28 18:44 UTC by TheOneAndOnlyCreeperJoe

One step closer to becoming a totalitarian server.

Adds logs to chemistry explosions, pipe bomb explosions, door charges, explosive implants, AI explosions and flux anomaly explosions.
Adds logs to people drinking from the glass goblet.
All explosion logs now have a JMP button behind them.

2016-12-28 18:45 UTC, McBawbaggings commented
+1 yeah sick cunt fuck yeah

2016-12-28 18:45 UTC, ArcLumin commented
does this include plasma in cigar explosions?

2016-12-28 18:47 UTC, TheOneAndOnlyCreeperJoe commented
it doesn't include plasma cigars yet.

2016-12-28 18:47 UTC, JohnGinnane requested changes

2016-12-28 18:47 UTC, JohnGinnane commented on html/changelogs/Creeper Joe - totalitarian logging.yml
> +  - tweak: "Becoming a vampire trough the filled glass goblet is now properly logged."
"trough" > "through"

2016-12-28 18:48 UTC, JohnGinnane commented
Did you test all the explosions that you added logging to?

2016-12-28 18:49 UTC, TheOneAndOnlyCreeperJoe commented
All of them, yes.

2016-12-28 18:56 UTC, ArcLumin commented
"It's a classic case of "I don't know how it works it just works"" - Joe, 2016

code looks good, albeit I have no idea how the syndie bomb works on non-carbon life. IT JUST WERKS, it seems

2016-12-28 19:39 UTC, JohnGinnane approved these changes

2016-12-28 19:39 UTC, JohnGinnane commented
Code looks good

2016-12-29 02:05 UTC, Swagile commented
yes please our god creeper strikes

2016-12-29 16:53 UTC, JohnGinnane commented
Need @Hackole input

2016-12-29 17:36 UTC, TheOneAndOnlyCreeperJoe commented
Added logging for oil slime extract explosions too.

2016-12-30 08:05 UTC, Swagile commented
GM + 1, good shit

2016-12-30 09:35 UTC, SpankMasterson commented
ye

2016-12-31 12:18 UTC, TheOneAndOnlyCreeperJoe commented
this should have long been merged

2016-12-31 12:20 UTC, merged