Adds a new Hockey bloodsprts themed traitor item set.
HippieStationArchive/HippieStation13-1 pull request #3240
Opened 2017-01-01 22:10 UTC by GuyonBroadway

Adds a potent hockey themed bundle of items for traitors, that includes a potent set of armour with helmet, a two-handed weapon mounted on a backpack that is the bastard child of a powerfist and baseball bat, some fancy pants looking roller-skates, A belt that can deploy a special thrown item that deals damage, stamina damage and stuns a target upon hitting them, this has a cooldown of about ten seconds and has slots to store up to two of them, and a hockey skull mask for badass points.

This set is purchasable from the traitor uplink for 20tc.

The whole set is NODROP, once you put this shit on you go all in, the idea is it's like a chainsaw level rampage item on steroids.

The armour is syringe proof, fireproof and spaceworthy if worn with the helmet and mask and they all have some decent energy resistance. However the potent hockey stick weapon can only be deployed from it's back mounted holder which cannot be removed, so in order to fully use it's power you need to sacrifice some versatility. Also if you get stunbaton'd you are down for 10 like anyone else.

The belt deploys little holopucks to your hand that deal about 10 brute and 20 stamina damage when thrown, this is amplified by the baseball bat effect from the hockey stick. They can be caught and thrown back at you so be careful.

The stick deals 18 damage and has a powerfist like knockback effect. Due to how the throw code works if they hit a wall they take 10 extra damage that pierces armour and stuns them for a little while. Leaving them helpless as you slap them into the wall over and over. It must be used with both hands to make use of it's damage but you need a free hand to throw (and bat back) objects.

Sprites are made by Fury McFlurry (except the puck sprite, that's just the middle of the E-sheild)

Possible changes that may or may not be necessary.

-Buff/Nerf the damage of the pucks and/or the stick itself.
-Buff/nerf the protective values of the armour, including its resistances to space/fire/syringes
-Possibly make an item that strips you down and equips the set directly on you so people can't cherry pick the gear.(This is a snowflakey solution)

![hockeyset](https://cloud.githubusercontent.com/assets/22083966/21583219/e3dd385c-d06e-11e6-9d67-2fee6f60d9d3.PNG)
The reason the right foot looks a little stretched is because the hockey stick is held down like a real hockey stick when you onehand it so it lines up with the skates.

2017-01-01 22:15 UTC, Hackole commented
If it's all sorted out codewise +1, this is neat as holy hell

2017-01-01 22:17 UTC, GuyonBroadway commented
It's all been tested out and works, the only issue was Icon conflicts last PR.

2017-01-01 22:45 UTC, McBawbaggings commented
The prospect of thawcking someone across the station with a hockey stick is killer. +1

2017-01-01 23:15 UTC, FuryMcFlurry commented
sprites were in the work in 2016, thats crazy long.
 Glad it looks great ingame.

2017-01-02 02:05 UTC, JohnGinnane commented
Half way through code review, will continue tomorrow

2017-01-02 04:00 UTC, SpankMasterson commented
+1 contingent on successful code review

2017-01-02 06:43 UTC, Swagile commented
same, GM + 1 if code check passes

a brand spanking new feature is always welcome and we can revert it if its too OP

2017-01-03 18:07 UTC, JohnGinnane requested changes

2017-01-03 18:07 UTC, JohnGinnane commented on code/game/objects/items/weapons/hockey.dm
> +	playsound(loc, 'sound/weapons/resonator_blast.ogg', 50, 1)
Same but for specthrowsound

2017-01-03 18:07 UTC, JohnGinnane commented on code/game/objects/items/weapons/hockey.dm
> +			visible_message("<span class='danger'>[src] has been dazed by a holopuck!</span>", \
Don't use src, use name or something

2017-01-03 18:18 UTC, GuyonBroadway commented
Requested changes made.

2017-01-03 23:17 UTC, JohnGinnane commented on code/datums/uplink_item.dm
> +	desc = "The iconic extreme environment gear used by Ka-Nada special sport forces. Used to devastating effect during the great northern sports wars of the second great athletic republic. The unmistak
Okay so I have some questions on this:

Shouldn't "great northern sports wars" and "second great athletic republic" be capitalised?

Also lack of commas; "great protection from most, if not all, environmental hazards and combat threats, in addition to.... weapon of the Ka-Nada SSF, and all terrain..."

2017-01-03 23:18 UTC, JohnGinnane commented on code/game/objects/items/weapons/hockey.dm
> +	desc = "Holds and powers a Ka-Nada SSF Hockey Stick, A devastating weapon capable of knocking men around like toys and batting objects at deadly velocities."
Uncapitalise "A devastating"

2017-01-03 23:20 UTC, JohnGinnane commented on code/game/objects/items/weapons/hockey.dm
> +	desc = "A Belt mounted device that quickly fabricates hard-light holopucks that when thrown will stall and slow down foes dealing minor damage. Has a pouch to store a pair of spare pucks"
"holopucks that, when thrown, will stall.."

2017-01-03 23:22 UTC, JohnGinnane commented on code/game/objects/items/weapons/hockey.dm
> +	desc = "A Belt mounted device that quickly fabricates hard-light holopucks that when thrown will stall and slow down foes dealing minor damage. Has a pouch to store a pair of spare pucks"
"slow down does, dealing minor damage."

2017-01-03 23:22 UTC, JohnGinnane commented on code/modules/clothing/head/helmet.dm
> +	name = "Ka-Nada winter sport combat helmet."
Is it "winter sport" or "winter sports"?

2017-01-03 23:22 UTC, JohnGinnane commented on code/modules/clothing/masks/gasmask.dm
> +	name = "Ka-Nada Hokcey Mask"
"Hockey"

2017-01-03 23:22 UTC, JohnGinnane commented on code/modules/clothing/suits/armor.dm
> +	name = "Ka-Nada winter sport combat suit"
Same here, is it "sports" or "sport"?

2017-01-03 23:23 UTC, JohnGinnane commented
Code is good I just have minor gripes with capitals and grammar things. English isn't my best so let me know if it's wrong

2017-01-03 23:23 UTC, JohnGinnane approved these changes

2017-01-04 00:11 UTC, GuyonBroadway commented
Oh fuck off, one of the other sets just fucked my PR!!

2017-01-04 02:06 UTC, GuyonBroadway commented
CLOSING AND REMAKIGN DUE TO SPACEDONG FUCKERY!

2017-01-04 02:06 UTC, closed without merging