Fixes Vape
HippieStationArchive/HippieStation13-1 pull request #3290
Opened 2017-01-05 03:02 UTC by tortellinitony

You can no longer put unstable mutagen in an e-cig, and reagents are absorbed at a normal rate when smoking one.

2017-01-05 03:07 UTC, ArcLumin commented
Considering this also disables mutagen, this is more than a fix, it needs head input

2017-01-05 03:12 UTC, tortellinitony commented
darn

2017-01-05 04:02 UTC, SpankMasterson commented
So if you put unstable mutagen in an ecig it sparks and explodes? I mean I guess I'm ok with this. Why is it necessary?

2017-01-05 04:03 UTC, tortellinitony commented
people abuse vape to get all of the good mutations within 5 mins

2017-01-05 08:41 UTC, LufgtHuron commented
why don't we remove chemistry completely, I mean who the fuck needs healing any way right? its OP and unfair for antags that people can heal.

or maybe just port baymed, i mean you all seem to want a boring piece of shit game where nothing happens and everyone dies in one hit? sheesh.

2017-01-05 09:12 UTC, KittyKathy commented
If you are touching vapes how about fixing a issue with it I will outline it below also correct me if I am wrong as i am not sure I understand this 100%.
Vapes have a 25% chance to transfer the reagents it has each tick to the smoker but cigarettes have a constant transfer for some reason?

I think REAGENTS_METABOLISM is .4.
I think reagents.trans_to(C, REAGENTS_METABOLISM) actually does the transferring to the smokers body but does not actually cause reactions, which you removed for some reason?
I think var/fraction = min(REAGENTS_METABOLISM/reagents.total_volume, 1) and reagents.reaction(C, INGEST, fraction) are responsible for calling ingestion specific reactions from the reagents and don't really transfer reagents into the person not sure if i am right about that.

Vapes before this PR called the ingestion reaction every time it rolls yes on that 25% chance to transfer reagents but cigarettes only call the ingestion reaction 15% of the time but transfer reagents every tick.
Vapes should work the same way like cigarettes constant reagent transfer and a change for ingestion reaction.

The way it calculates the fraction variable seems a bit weird too.
it does min(.4/Total reagents,1) so the less reagents it has, more will be in the ingestion reaction?
Like a full vape would be min(.4/100,1) which will make the fraction variable .004?
While a almost empty vape with 1 unit would be min(.4/1,1) which will make the fraction variable .4?
Would it not make more sense to make a full vape use more reagents for the ingestion reaction than a almost empty one?

I think reagents.remove_any(REAGENTS_METABOLISM) is where it actually removes reagents from the vape but this gets called every tick regardless if the vape passes the 25% roll to transfer to the smoker which makes no sense.

Just a note but because reagents have different metabolism rates anything on the default .4 will pretty much be instantly used up if it was the only chemical in the vape(more chemicals divides how much of each chemical is transferred by the amount of different chemicals so 2 chemicals will transfer .2 each tick) so to actually get a constant dose from smoking currently you need to use cigarette (Cohiba has the most capacity) use one chemical with a lower than default .4 metabolism rate to make sure you actually gain reagents each tick instead of it being used up instantly.

In conclusion who coded this seriously it makes no sense I don't think anyone actually understands it. It was probably a shitty copy paste of cigarette code and changing things they don't understand until it was good enough.

2017-01-05 09:25 UTC, Kierany9 commented
>In conclusion who coded this seriously it makes no sense I don't think anyone actually understands it. It was probably a shitty copy paste of cigarette code and changing things they don't understand until it was good enough.

best tldr

2017-01-05 11:36 UTC, JohnGinnane commented
I would think that e-cigs should function **the exact same as cigarettes**, if not for some slightly different figures (capacity, percentage of ingestion, etc.). I can review the e-cigs to see what the issue is. While on the same note shouldn't normal cigars and cigarettes spawn (even small) plumes of smoke every few ticks just like vapes, possibly with added carbon dioxide?

2017-01-05 12:08 UTC, McBawbaggings commented
Eh, what's to stop people taking unstable mutagen and injecting it to regular fags?

2017-01-05 12:09 UTC, IvanTheCracka commented
>lufght mad that he cant murder all the station without people being able to stun him, retrieve his corpse for gibbing; and use TK from a vent 

>GOYS MAKE THE GAME FUN FOR ME I WANNA KEEP DOING THIS EVERY ROUND OI VEY

2017-01-05 12:10 UTC, Kierany9 commented
flood the vents

burn the heretics

2017-01-05 16:36 UTC, tortellinitony commented
> You can vape mutagen again.

Instead of targeting the vapes, like Mcbaw mentioned, mutagen can still be abused. I change it so that mutagen will not grant hulk, which is what causes it to be exploitable.

Additionally, e-cigs should behave exactly like their normal counterparts. Feel free to check this.

2017-01-05 16:52 UTC, McBawbaggings commented on code/modules/reagents/Chemistry-Reagents/Toxin-Reagents.dm
> +			HM.force_give(M)
I'd just override the randmutg() proc with a second variable that defaults to 0. Then force it to be randmutg(M, 1) and if the second argument is true, it doesn't give certain powers (for example, hulk).

2017-01-05 16:56 UTC, tortellinitony commented on code/modules/reagents/Chemistry-Reagents/Toxin-Reagents.dm
> +			HM.force_give(M)
this is already the same as what the proc does except it rolls every time instead of sometimes not rolling if it picked hulk

2017-01-05 17:02 UTC, Spacedong commented
holy fuck merge this is priority its gamebreaking

2017-01-05 19:55 UTC, SpankMasterson commented
I like tony's idea of editting mutagen not to grant power blocks.

2017-01-05 20:02 UTC, ghost requested changes
This doesn't do exactly what I suggested it would do, so it would probably be better to address that.

2017-01-05 20:02 UTC, McBawbaggings commented on code/game/dna.dm
> +/proc/randmutg(mob/living/carbon/M, var/nohulk as num)
Honestly, try changing the "var/nohulk as num" to "var/nohulk = 0"

2017-01-05 20:02 UTC, McBawbaggings commented on code/game/dna.dm
> +	if(nohulk == 0)
And if you do that, just change "nohulk == 0" to "!nohulk"

2017-01-05 23:23 UTC, KittyKathy commented
Vape code is probably fine just one thing, not sure why reagents.remove_any(REAGENTS_METABOLISM) is not right after reagents.trans_to(C, REAGENTS_METABOLISM) in the same if statement. This was probably just copied from cigarette code to allow cigarettes to use up the reagents once lit even if you are not smoking it. So it probably does not matter as I think Vapes stop processing as a object when you are not smoking it so it won't lose reagents unless you are smoking it.

Also you know there is a mutation that makes you feel strange right and mutates you? Can that give you hulk? If it can did you stop it from giving you hulk in this PR?

2017-01-05 23:36 UTC, tortellinitony commented
yes

2017-01-06 15:28 UTC, ghost approved these changes

2017-01-06 15:29 UTC, McBawbaggings commented
Yeah good code +1

2017-01-08 03:32 UTC, ArcLumin commented on code/game/objects/items/weapons/cigs_lighters.dm
> +			reagents.remove_any(REAGENTS_METABOLISM)
Looking at the full file, it works. This is all good

2017-01-08 03:34 UTC, ArcLumin commented
@SpankMasterson Need your full approval and it's good to merge

2017-01-08 03:36 UTC, Dudeinyourbackyard commented
go ahead

2017-01-08 03:36 UTC, ArcLumin commented
Sure thing my dude

2017-01-08 03:36 UTC, merged

2017-01-08 03:36 UTC, SpankMasterson commented
+1

2017-01-08 03:37 UTC, ArcLumin commented
TOO SLOW SPANKY

2017-01-08 03:37 UTC, SpankMasterson commented
am i late?

2017-01-08 03:37 UTC, SpankMasterson commented
fuck you

2017-01-08 03:37 UTC, ArcLumin commented
But it's the thought that counts

2017-01-08 03:37 UTC, SpankMasterson commented
i cant even merge anymore, someone took my privs.

2017-01-08 03:37 UTC, ArcLumin commented
So sad my dude